### ISSUE TITLE
java.lang.NoSuchMethodError - me.i509.fabric.bulkyshulkies.recipe.AbstractShulkerBoxUpgradeRecipe.<init>(AbstractShulkerBoxUpgradeRecipe.java:46)

### ISSUE THREAD

**Issue by ghost** [i509VCB/CursedShulkerBoxes#3]
I'm getting this error when starting a server with the mod loaded.

> [22:20:47] [Server thread/ERROR]: Failed to reload data packs
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.class_1869.method_8112()Ljava/lang/String;
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908) ~[?:1.8.0_232]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1489) [intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:468) [intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:382) [intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:218) [intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:627) [intermediary-minecraft_server-1.15.1.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoSuchMethodError: net.minecraft.class_1869.method_8112()Ljava/lang/String;
	at me.i509.fabric.bulkyshulkies.recipe.AbstractShulkerBoxUpgradeRecipe.<init>(AbstractShulkerBoxUpgradeRecipe.java:46) ~[bulkyshulkies-1.0.1.jar:?]
	at me.i509.fabric.bulkyshulkies.recipe.AbstractShulkerBoxUpgradeRecipeSerializer.read(AbstractShulkerBoxUpgradeRecipeSerializer.java:36) ~[bulkyshulkies-1.0.1.jar:?]
	at me.i509.fabric.bulkyshulkies.recipe.AbstractShulkerBoxUpgradeRecipeSerializer.method_8121(AbstractShulkerBoxUpgradeRecipeSerializer.java:33) ~[bulkyshulkies-1.0.1.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:115) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:53) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_232]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_232]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:724) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:718) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-minecraft_server-1.15.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1487) ~[intermediary-minecraft_server-1.15.1.jar:?]
	... 5 more

**Comment by Eliteneet** [comment]
Yup I'm having the same issue on my server, makes shulker boxes uncraftable.

**Comment by i509VCB** [comment]
Will look into this.

**Comment by i509VCB** [comment]
Alright I figured out the issue, I seem to be calling getGroup (It's a client only method) on a server, this fix should take a few minutes and I'll push an update.

@Eliteneet @Katorone

**Comment by Eliteneet** [comment]
Awesome good to hear, I've been waiting so long for this mod to come to fabric. Happy its here!

**Comment by i509VCB** [comment]
Fixed in latest commit, I'll throw a release on CF and GitHub in a min.

**Comment by ghost** [comment]
Thanks a bunch!
