### ISSUE TITLE
Mod Icon is invalid

### ISSUE THREAD

**Issue by PanoptesDreams** [i509VCB/CursedShulkerBoxes#4]
Console spits about a bunch of errors, it can't load your mods icon because it's not square.

I've made a "fixed" icon

![icon](https://user-images.githubusercontent.com/55162814/72110807-00d48b00-339e-11ea-9385-bc9d23c4b610.png)

**Comment by PanoptesDreams** [comment]
Note this does not affect the mod in an way. This is it:

[11:38:36] [main/ERROR]: Invalid icon for mod Bulky Shulkies
java.lang.IllegalStateException: Must be square icon
	at org.apache.commons.lang3.Validate.validState(Validate.java:829) ~[commons-lang3-3.5.jar:3.5]
	at io.github.prospector.modmenu.gui.ModListEntry.createIcon(ModListEntry.java:92) [modmenu-1.8.3+build.19.jar:?]
	at io.github.prospector.modmenu.gui.ModListEntry.bindIconTexture(ModListEntry.java:117) [modmenu-1.8.3+build.19.jar:?]
	at io.github.prospector.modmenu.gui.ModListEntry.render(ModListEntry.java:49) [modmenu-1.8.3+build.19.jar:?]
	at io.github.prospector.modmenu.gui.ModListWidget.renderList(ModListWidget.java:227) [modmenu-1.8.3+build.19.jar:?]
	at net.minecraft.class_350.render(class_350.java:196) [intermediary-minecraft-1.15.1-client.jar:?]
	at io.github.prospector.modmenu.gui.ModListScreen.render(ModListScreen.java:237) [modmenu-1.8.3+build.19.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:604) [intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:947) [intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:585) [intermediary-minecraft-1.15.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:202) [intermediary-minecraft-1.15.1-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.2+build.175.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.175.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.175.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by i509VCB** [comment]
I noticed that when publishing to curseforge that the icon wasn't square but thanks for reminding me to update the icon so it doesn't nag any more.

**Comment by i509VCB** [comment]
This should be fixed in the latest build for 1.15.2-pre1. This should be backwards compatible with 1.15.1
